(()=>{
'use strict';
const state={lang:localStorage.getItem('dj-breeze-lang')||'sv',cfg:null,settings:null,eras:[],gallery:[],events:[],tracks:[],activeTrack:null};
const T={
sv:{navAbout:'Om',navSound:'Sound',navLive:'Live',navArchive:'Arkiv',navBooking:'Bokning',hideMenu:'Dölj meny',showMenu:'Visa meny',bookDj:'Boka DJ Breeze',meetDj:'Möt DJ Breeze',soundHeading:'BYGGT PÅ<br>KLASSIKER.',soundIntro:'90-talet lade grunden. 00-talet blev sweet spot. Men rummet bestämmer alltid nästa låt.',liveHeading:'DU VAR TVUNGEN<br>ATT VARA DÄR.',liveIntro:'Riktiga rum, riktiga människor och kvällar där musiken gjorde jobbet.',archiveHeading:'FLYERS ÄR<br>EN DEL AV HISTORIEN.',archiveIntro:'Utvalda event, artwork och kvällar som byggt DJ Breeze-världen.',bookingHeading:'LÅT OSS FLYTTA<br>RUMMET.',bookingIntro:'Välj typ av event och skicka detaljerna direkt. Förfrågan hamnar i DJ Breeze admin.',wedding:'Bröllop',eventType:'Eventtyp',date:'Datum',city:'Stad / plats',venue:'Venue (valfritt)',name:'Namn',phone:'Telefon (valfritt)',guests:'Antal gäster (valfritt)',details:'Detaljer',detailsPlaceholder:'Tid, publik, upplägg, musik, budget eller annat DJ Breeze bör känna till.',sendRequest:'Skicka bokningsförfrågan',sending:'Skickar…',sent:'Tack! Din förfrågan är skickad. DJ Breeze återkommer.',sendError:'Något gick fel. Försök igen om en stund.',rateLimit:'Vänta en minut innan du skickar en ny förfrågan.',nowPlaying:'NU SPELAS',archive:'ARKIV',live:'LIVE'},
en:{navAbout:'About',navSound:'Sound',navLive:'Live',navArchive:'Archive',navBooking:'Booking',hideMenu:'Hide menu',showMenu:'Show menu',bookDj:'Book DJ Breeze',meetDj:'Meet DJ Breeze',soundHeading:'BUILT ON<br>CLASSICS.',soundIntro:'The 90s built the foundation. The 00s became the sweet spot. The room always decides what comes next.',liveHeading:'YOU HAD TO<br>BE THERE.',liveIntro:'Real rooms, real people and nights where the music did the work.',archiveHeading:'THE FLYERS<br>ARE PART OF IT.',archiveIntro:'Selected events, artwork and nights that shaped the DJ Breeze world.',bookingHeading:"LET'S MOVE<br>THE ROOM.",bookingIntro:'Choose your event type and send the details directly. Your request lands in the DJ Breeze admin inbox.',wedding:'Wedding',eventType:'Event type',date:'Date',city:'City / location',venue:'Venue (optional)',name:'Name',phone:'Phone (optional)',guests:'Guest estimate (optional)',details:'Details',detailsPlaceholder:'Time, crowd, setup, music, budget or anything DJ Breeze should know.',sendRequest:'Send booking request',sending:'Sending…',sent:'Thanks! Your request has been sent. DJ Breeze will get back to you.',sendError:'Something went wrong. Please try again shortly.',rateLimit:'Please wait one minute before sending another request.',nowPlaying:'NOW PLAYING',archive:'ARCHIVE',live:'LIVE'}};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const safeUrl=v=>{const s=String(v||'').trim();if(!s)return'';if(/^https:\/\//i.test(s)||/^data:image\//i.test(s)||/^assets\//.test(s)||/^\.\.?\//.test(s))return s;return''};
function tr(k){return (T[state.lang]&&T[state.lang][k])||k}
function setLang(lang){state.lang=lang==='en'?'en':'sv';localStorage.setItem('dj-breeze-lang',state.lang);document.documentElement.lang=state.lang;$$('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));$$('[data-i18n]').forEach(el=>{el.textContent=tr(el.dataset.i18n)});$$('[data-i18n-html]').forEach(el=>{el.innerHTML=tr(el.dataset.i18nHtml)});$$('[data-i18n-placeholder]').forEach(el=>{el.placeholder=tr(el.dataset.i18nPlaceholder)});applySettings();renderEras();renderGallery();renderEvents();renderTrackMeta()}
async function loadConfig(){try{const r=await fetch('content/backend.json',{cache:'no-store'});if(!r.ok)throw Error('config');const cfg=await r.json();if(!cfg.enabled||!cfg.url||!cfg.anonKey)throw Error('config disabled');state.cfg=cfg;return true}catch(e){console.warn('CMS config unavailable',e);return false}}
function apiHeaders(extra={}){return{apikey:state.cfg.anonKey,Authorization:'Bearer '+state.cfg.anonKey,...extra}}
async function getRows(path){const r=await fetch(state.cfg.url.replace(/\/$/,'')+'/rest/v1/'+path,{headers:apiHeaders(),cache:'no-store'});if(!r.ok)throw Error('API '+r.status);return r.json()}
async function loadCms(){if(!state.cfg)return;try{const [settings,eras,gallery,events,tracks]=await Promise.all([getRows('site_settings?id=eq.1&select=*'),getRows('sound_eras?published=eq.true&select=*&order=sort_order.asc'),getRows('gallery_images?published=eq.true&select=*&order=sort_order.asc'),getRows('events?published=eq.true&select=*&order=sort_order.asc,event_date.desc.nullslast'),getRows('music_tracks?published=eq.true&select=*&order=sort_order.asc')]);state.settings=settings[0]||null;state.eras=eras||[];state.gallery=gallery||[];state.events=events||[];state.tracks=tracks||[];state.activeTrack=state.tracks.find(x=>x.active)||state.tracks[0]||null;applySettings();renderEras();renderGallery();renderEvents();setupMusicFromCms()}catch(e){console.warn('CMS content unavailable',e)}}
function fieldByLang(base,obj){if(!obj)return'';return obj[base+'_'+state.lang]||obj[base+'_en']||obj[base+'_sv']||''}
function applySettings(){const s=state.settings;if(!s)return;$('#heroKicker').textContent=fieldByLang('hero_kicker',s)||'OFFICIAL SITE • ARTIST / DJ';$('#heroCopy').textContent=fieldByLang('hero_copy',s);$('#aboutHeading').innerHTML=esc(fieldByLang('about_heading',s)).replace(/DJ BREEZE\.?$/i,'<br>DJ BREEZE.');$('#aboutLead').textContent=fieldByLang('about_lead',s);$('#aboutBody').textContent=fieldByLang('about_body',s);$('#footerCopy').textContent=fieldByLang('footer',s)||'DJ Breeze — Official';if(s.instagram_url){$('#instagramLink').href=s.instagram_url}const h=safeUrl(s.hero_image_url);if(h){$('#heroImage').style.backgroundImage=`url("${h.replace(/"/g,'%22')}")`;$('#heroImage').setAttribute('aria-label',fieldByLang('hero_image_alt',s)||'DJ Breeze')}if(s.default_language&&!localStorage.getItem('dj-breeze-lang')&&state.lang!==s.default_language)setLang(s.default_language);if(s.site_sound_volume!=null){$('#siteAudio').volume=Number(s.site_sound_volume);$('#volumeSlider').value=String(s.site_sound_volume)}$('#siteAudio').loop=s.site_sound_loop!==false;if(s.site_sound_enabled===false)$('#musicPlayer').style.display='none'}
function renderEras(){const grid=$('#eraGrid');if(!grid)return;if(!state.eras.length){if(!state.cfg)return;grid.innerHTML='<div class="loading-card">No sound cards published.</div>';return}grid.innerHTML=state.eras.map(x=>`<article class="era-card"><img loading="lazy" src="${esc(safeUrl(x.image_url)||'assets/images/soulful-classics.jpg')}" alt="${esc(fieldByLang('title',x))}"><div class="era-card-content"><div class="era-label">${esc(x.label||'')}</div><h3>${esc(fieldByLang('title',x))}</h3><p>${esc(fieldByLang('description',x))}</p></div></article>`).join('')}
function renderGallery(){const grid=$('#galleryGrid');if(!grid)return;if(!state.gallery.length){if(!state.cfg)return;grid.innerHTML=fallbackGallery();return}grid.innerHTML=state.gallery.map((x,i)=>`<figure class="gallery-card ${i===0?'featured':''}"><img loading="lazy" src="${esc(safeUrl(x.file_url))}" alt="${esc(fieldByLang('alt',x)||'DJ Breeze live')}"><span>${esc(fieldByLang('caption',x)||tr('live'))}</span></figure>`).join('')}
function fallbackGallery(){return['dj-breeze-portrait.jpg','outdoor-event.jpg','crowd-live.jpg','booth-live.jpg','promo-artwork.jpg'].map((f,i)=>`<figure class="gallery-card ${i===0?'featured':''}"><img loading="lazy" src="assets/images/${f}" alt="DJ Breeze live"><span>${i===0?'ARTIST / PORTRAIT':'LIVE'}</span></figure>`).join('')}
function renderEvents(){const grid=$('#archiveGrid');if(!grid)return;if(!state.events.length){if(!state.cfg)return;grid.innerHTML='<div class="loading-card">No archive items published.</div>';return}grid.innerHTML=state.events.map((x,i)=>{const title=fieldByLang('title',x);const meta=[x.venue,x.city,x.event_date].filter(Boolean).join(' · ')||tr('archive');return`<article class="archive-card"><div class="archive-image"><img loading="lazy" src="${esc(safeUrl(x.flyer_url)||'assets/images/promo-artwork.jpg')}" alt="${esc(title)}"><div class="archive-overlay"><small>${String(i+1).padStart(2,'0')} / ${esc((x.category||tr('archive')).toUpperCase())}</small><h3>${esc(title)}</h3></div></div><div class="archive-meta">${esc(meta)}</div></article>`}).join('')}
function setupMenu(){const header=$('#siteHeader'),show=$('#showMenuBtn'),hide=$('#hideMenuBtn'),mobile=$('#mobileMenu'),toggle=$('#menuToggle'),close=$('#mobileClose');const setHidden=v=>{header.classList.toggle('hidden',v);show.classList.toggle('visible',v);sessionStorage.setItem('dj-menu-hidden',v?'1':'0')};hide.addEventListener('click',()=>setHidden(true));show.addEventListener('click',()=>setHidden(false));if(sessionStorage.getItem('dj-menu-hidden')==='1')setHidden(true);const setMobile=open=>{mobile.hidden=!open;toggle.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''};toggle.addEventListener('click',()=>setMobile(mobile.hidden));close.addEventListener('click',()=>setMobile(false));$$('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>setMobile(false)))}
function setupReveal(){const els=$$('.reveal');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('in'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});els.forEach(e=>io.observe(e))}
function setupBooking(){const chips=$$('#bookingTypeChips button'),sel=$('#bookingType');chips.forEach(b=>b.addEventListener('click',()=>{sel.value=b.dataset.type;chips.forEach(x=>x.classList.toggle('active',x===b));$('#bookingForm').scrollIntoView({behavior:'smooth',block:'center'})}));sel.addEventListener('change',()=>chips.forEach(x=>x.classList.toggle('active',x.dataset.type===sel.value)));chips[0].classList.add('active');$('#bookingForm').addEventListener('submit',submitBooking)}
async function submitBooking(e){e.preventDefault();const status=$('#bookingStatus'),btn=$('.submit-btn');status.className='form-status';if($('#websiteField').value)return;const last=Number(localStorage.getItem('dj-booking-last')||0);if(Date.now()-last<60000){status.textContent=tr('rateLimit');status.classList.add('error');return}if(!e.currentTarget.reportValidity())return;if(!state.cfg){status.textContent=tr('sendError');status.classList.add('error');return}const payload={event_type:$('#bookingType').value,event_date:$('#bookingDate').value,city:$('#bookingCity').value.trim(),venue:$('#bookingVenue').value.trim()||null,guest_estimate:$('#bookingGuests').value?Number($('#bookingGuests').value):null,customer_name:$('#bookingName').value.trim(),customer_email:$('#bookingEmail').value.trim(),customer_phone:$('#bookingPhone').value.trim()||null,message:$('#bookingMessage').value.trim()||null,status:'new',source:'website',honeypot:''};btn.disabled=true;status.textContent=tr('sending');try{const r=await fetch(state.cfg.url.replace(/\/$/,'')+'/rest/v1/bookings',{method:'POST',headers:apiHeaders({'Content-Type':'application/json','Prefer':'return=minimal'}),body:JSON.stringify(payload)});if(!r.ok)throw Error(await r.text());localStorage.setItem('dj-booking-last',String(Date.now()));status.textContent=tr('sent');status.classList.add('success');e.currentTarget.reset();chipsReset()}catch(err){console.warn(err);status.textContent=tr('sendError');status.classList.add('error')}finally{btn.disabled=false}}
function chipsReset(){const chips=$$('#bookingTypeChips button');chips.forEach((x,i)=>x.classList.toggle('active',i===0))}
function fmt(t){if(!Number.isFinite(t))return'0:00';const m=Math.floor(t/60),s=Math.floor(t%60);return`${m}:${String(s).padStart(2,'0')}`}
function setupMusic(){const a=$('#siteAudio'),toggle=$('#musicToggle'),progress=$('#musicProgress'),vol=$('#volumeSlider'),mute=$('#muteBtn'),collapse=$('#playerCollapse'),player=$('#musicPlayer');const sync=()=>{player.classList.toggle('playing',!a.paused);$('#musicIcon').textContent=a.paused?'▶':'Ⅱ'};toggle.addEventListener('click',async()=>{try{a.paused?await a.play():a.pause()}catch(e){console.warn(e)}sync()});a.addEventListener('play',sync);a.addEventListener('pause',sync);a.addEventListener('loadedmetadata',()=>{$('#duration').textContent=fmt(a.duration)});a.addEventListener('timeupdate',()=>{$('#elapsed').textContent=fmt(a.currentTime);if(a.duration)progress.value=String(Math.round(a.currentTime/a.duration*1000))});progress.addEventListener('input',()=>{if(a.duration)a.currentTime=Number(progress.value)/1000*a.duration});vol.addEventListener('input',()=>{a.volume=Number(vol.value);a.muted=false;mute.textContent='VOL'});mute.addEventListener('click',()=>{a.muted=!a.muted;mute.textContent=a.muted?'MUTE':'VOL'});collapse.addEventListener('click',()=>player.classList.toggle('collapsed'));document.addEventListener('pointerdown',()=>{if(state.settings?.site_sound_autoplay&&a.paused)a.play().catch(()=>{})},{once:true})}
function setupMusicFromCms(){const a=$('#siteAudio');if(state.activeTrack){const u=safeUrl(state.activeTrack.audio_url);if(u){const src=a.querySelector('source');if(src.getAttribute('src')!==u){src.src=u;a.load()}}renderTrackMeta()}}
function renderTrackMeta(){if(state.activeTrack)$('#trackTitle').textContent=state.activeTrack.title||'DJ Breeze Mix'}
function initFallbackContent(){state.eras=[{label:'01 / FOUNDATION',title_sv:'MITTEN AV 90-TALET',title_en:'MID 90s',description_sv:'Golden-era hip-hop, R&B, soul och låtar som fortfarande bär minnen.',description_en:'Golden-era hip-hop, R&B, soul and records with real memories attached.',image_url:'assets/images/soulful-classics.jpg'},{label:'02 / SWEET SPOT',title_sv:'TIDIGT 00-TAL',title_en:'EARLY 00s',description_sv:'Anthems, slow jams och klubbklassiker.',description_en:'Anthems, slow jams and club classics.',image_url:'assets/images/throwback-fridays.jpg'},{label:'03 / RIGHT NOW',title_sv:'RUMMET FÖRST',title_en:'ROOM FIRST',description_sv:'Rummet bestämmer alltid nästa låt.',description_en:'The room always decides what comes next.',image_url:'assets/images/rnb-afterwork.jpg'}];state.gallery=[];state.events=[['R&B Afterwork','rnb-afterwork.jpg'],['Soulful Classics','soulful-classics.jpg'],['R&B Sounds','rnb-sounds.jpg'],['Who Told You?','who-told-you.jpg']].map((x,i)=>({title_sv:x[0],title_en:x[0],flyer_url:'assets/images/'+x[1],category:'archive',sort_order:(i+1)*10}));renderEras();renderGallery();renderEvents()}
async function boot(){initFallbackContent();setupMenu();setupReveal();setupBooking();setupMusic();$$('.lang-btn').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));setLang(state.lang);const ok=await loadConfig();if(ok)await loadCms();setTimeout(()=>$('#pageLoader').classList.add('done'),180)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();